### PR TITLE
Add the Dungeon Crawl Classics (dcc) system

### PR DESCRIPTION
**Pull request by cyface**
Hello!

 I'm the maintainer of the DCC system, and I found your module useful! I've created this PR to add support for DCC.

Thank you!

### CODE REVIEW

**Comment by mybigfriendjo** [comment]
Thx for your contribution. Not in front of my PC currently but i'll take a look at it tomorrow evening so I can also create a new version on foundry. 👍

**Comment by cyface** [comment]
@mybigfriendjo Thank you!

**Comment by mybigfriendjo** [comment]
wasn't yesterday after all. but it's merged now and a new version is up on the package repository on foundry. thx again.

**Comment by cyface** [comment]
Thank you!

**Comment by mybigfriendjo** [comment]
Just took a more in-depth look at the system, and while i found some enrichments for classnames, spellresults and some effects within item sheets i don't believe you enrich formulas for inline rolls?

i might consider adding you to the non-enriched section which doesn't change anything about the function of the module but will put a small warning the first time the module is activated that inline rolls aren't a thing for the system.

would that be ok or am i missing something in the system as far as enrichments go?

**Comment by cyface** [comment]
I was trying to figure out which list we should be on; but before I answer,
how would I enrich those formulas?

**Comment by mybigfriendjo** [comment]
the *[Config](https://foundryvtt.com/api/interfaces/client.TextEditorEnricherConfig.html)* of the *[TextEditor](https://foundryvtt.com/api/classes/client.TextEditor.html)* can have enrichers that look for patterns and - when found - can reformat / rework those patterns into something different according to the enricher object assigned.

a good example of a module that does (or did since dnd5e has it builtin now) this very thing would maybe be [inline-roll-cmd](https://github.com/kaelad02/inline-roll-cmd/tree/main)
specifically the core file will likely be interesting -> https://github.com/kaelad02/inline-roll-cmd/blob/main/src/inline-roll-cmd.js#L20

hope it helps

**Comment by mybigfriendjo** [comment]
here is where dnd5e adds those things -> https://github.com/foundryvtt/dnd5e/blob/4b4f63cd73ca686d1f3b1f0c641c092fe88020dd/module/enrichers.mjs#L15

**Comment by cyface** [comment]
Interesting! We do that all over the official modules - where there are
[[/roll 1d20]] type embeds all over.

We have a lot of fancy rolls for spell rolls and such, but they don't
enrich like this, they are just custom card types.

So up to you! I'm not thinking we will add this to regular chat cards.

**Pull request merged**
